name: HCF
version: '${project.version}'
author: Hackusate_PvP
main: dev.hcr.hcf.HCF
depend: [ProtocolLib]
commands:
  balance:
    aliases: [bal]
    description: View your current balance.
  claimbonuschest:
    description: Claim donator items.
    permission: hcf.commands.donor.claimbonuschest
  economy:
    aliases: [eco]
    description: Economy management command.
    permission: hcf.commands.admin.economy
  faction:
    aliases: [factions, f]
    description: Main faction command.
  pay:
    description: Send in-game currency to another user.
  sotw:
    aliases: [startoftheworld]
    description: Managers the SOTW event.
    permission: hcf.commands.admin.sotw